### ISSUE TITLE
please provide manylinux wheels

### ISSUE THREAD

**Issue by costela** [ndparker/rcssmin#10]
Hi,

is it feasible to reuse the solution for ndparker/rjsmin#14 here as well?

Thanks!

**Comment by ndparker** [comment]
Yes. Unfortunately not immediately. I'm currently updating and modernizing the project structures and management procedures. rjsmin was the first to release. But rcssmin should be happening soon enough.

**Comment by costela** [comment]
Great! Thanks for the feedback and all the work!

**Comment by hernantz** [comment]
Has there been any update on this?

**Comment by ndparker** [comment]
Fixed with 1.1.0.
