### ISSUE TITLE
rcssmin not working on ubuntu bionic.

### ISSUE THREAD

**Issue by paolobenve** [ndparker/rcssmin#11]
On my ubuntu bionic system, `rcssmin` installed with either `python-rcssmin` or `python3-rcssmin` doesn't work. The command `python -m rcssmin` never ends.

**Comment by ndparker** [comment]
Hi,

is `python -m rcssmin` the exact command you're using? Because this expects data (i.e. your css) from stdin.

Cheers,

**Comment by paolobenve** [comment]
I'm using that command in order to know whether the module is there. Shouldn't it work?

**Comment by ndparker** [comment]
Uhm, well, yes, it does. As said, it's expecting input.

If you simply want to know it's there, you should try importing it, e.g.: `python -c 'import rcssmin'`.
`python -m module` *runs* a module as a script. That's not a good idea as a generic way to test existence of a module.

**Comment by paolobenve** [comment]
thank you!
