### ISSUE TITLE
Mangles URLs with spaces

### ISSUE THREAD

**Issue by Ben-Brady** [ndparker/rcssmin#15]
It you give the following css to cssmin
```css
@import url('https://fonts.googleapis.com/css?family=Open Sans:700');"
```
it converts it to 
```css
@import url('https://fonts.googleapis.com/css?family=OpenSans:700');"
```

which messes up the font import.

**Comment by ndparker** [comment]
Hi,

thanks for your report.
The behaviour is correct, though. Spaces in URLs need to be encoded (as %20).
