### ISSUE TITLE
Invalid selectors processing

### ISSUE THREAD

**Issue by a-sakharov** [ndparker/rcssmin#16]
Hello, I faced a bug.

It's removing space inside item path, so
`echo '#a .b {}' | python -m rjsmin` producing `#a.b{}` instead of `#a .b{}`
But for some reason it's keeping some of the newlines, while it's not really needed.

**Comment by ndparker** [comment]
Hi,

Thanks for your report.

```shell
$ echo '#a .b {}' | python -m rcssmin
#a .b{}
```

I do believe, if you actually use rcssmin instead of rjsmin it should work as expected :-)

Cheers,

**Comment by a-sakharov** [comment]
Oh, sorry. Looks like I was too tired that day.
Then that's not a valid issue.

Thanks.
